name: Java CI with Maven

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # Change this to the version of JDK you want to use
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml